Visify/Controllers/GraphController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using Visify.Areas.Identity.Data;
using Visify.Models;
using Visify.Services;

namespace Visify.Controllers
{
    
    [Authorize]
    public class GraphController : Controller
    {

        private readonly UserManager<VisifyUser> _userManager;
        private readonly ILogger<GraphController> logger;

        public GraphController(UserManager<VisifyUser> um, ILogger<GraphController> _logger) {
            this._userManager = um;
            this.logger = _logger;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(ArtistCollabGraph));
        }

        public IActionResult ArtistCollabGraph() {
            return View();
        }


        public IActionResult ArtistSongGroupGraph() {
            return View();
        }


        private class FDGNode {
            public readonly string id;
            public readonly int group;
            public readonly string label;
            public readonly int level;
            public int size;

            public FDGNode(string id, int group, string label, int level, int size) {
                this.id = id;
                this.group = group;
                this.label = label;
                this.level = level;
                this.size = size;
            }
        }

        private class FDGEdge {
            public readonly string source;
            public readonly string target;
            public double strength;
            public readonly List<Dictionary<string, string>> tracks = new List<Dictionary<string, string>>();

            public FDGEdge(string source, string target, double strength) {
                this.source = source;
                this.target = target;
                this.strength = strength;
            }
        }

        private class FDGCollabEdge : FDGEdge {

            public new readonly List<string> tracks = new List<string>();

            public FDGCollabEdge(string source, string target, double strength, List<string> tracks) : base(source, target, strength) {
                this.tracks = tracks;
            }
        }


        private class TDict {
            public readonly string name;
            public readonly string sid;
            public readonly string album;
            public readonly int size;

            public TDict(string name, string sid, string album, int size) {
                this.name = name;
                this.sid = sid;
                this.album = album;
                this.size = size;
            }
        }

        /// <summary>
        /// Artist Song Group Count api method
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("Graph/artistsonglink")]
        public async Task<IActionResult> GetArtistLinks() {

            VisifyUser user = await _userManager.GetUserAsync(User);
            if (user == null) {
                logger.LogInformation($"Tried to get Artist Song Count graph data for user {_userManager.GetUserId(User)}, but user did not exist");
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            // Get the tracks and artists
            VOption<IList<VisifySavedTrack>> stracks = await DatabaseService.GetUsersSavedTracks(user.Id, limit:10_000);
            if (!stracks.WasSuccess) {
                logger.LogError($"Failed to retreive saved tracks for user {_userManager.GetUserId(User)}", stracks.ErrorMessage);
                return Json("FAILED");
            }

            // create a proper d3 structure
            Dictionary<string, FDGNode> nodes = new Dictionary<string, FDGNode>();
            Dictionary<string, FDGEdge> edges = new Dictionary<string, FDGEdge>();

            foreach (VisifySavedTrack vst in stracks.Value) {
                string tid = $"tid_{vst.VisifyTrack.SpotifyId}";
                string[] idarr = new string[2];
                foreach (VisifyArtist va in vst.VisifyTrack.Artists) {
                    string sid = $"aid_{va.SpotifyId}";
                    idarr[0] = sid;
                    idarr[1] = tid;
                    Array.Sort(idarr);
                    string lid0 = String.Join("", idarr);
                    string lid1 = $"at_{lid0}";
                    if (!nodes.ContainsKey(sid)) {
                        nodes.Add(sid, new FDGNode(sid, 0, va.ArtistName, 0, 1));
                    }
                    else {
                        nodes[sid].size += 1;
                    }
                    nodes.Add(lid1, new FDGNode(lid1, 0, vst.VisifyTrack.TrackName, 1, 1));
                    if (!edges.ContainsKey(lid0)){
                        edges.Add(lid0, new FDGEdge(lid1, sid, 0.1));
                    }
                }
            }

            Dictionary<string, object> keys = new Dictionary<string, object>() {
                {"nodes", nodes.Values },
                {"links", edges.Values }
            };
            return Json(keys);
        }

        /// <summary>
        /// Artist Song Group Count api method
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("Graph/artistcollablink")]
        public async Task<IActionResult> GetArtistCollabLinks() {

            VisifyUser user = await _userManager.GetUserAsync(User);
            if (user == null) {
                logger.LogInformation($"Tried to get Artist Collab Link graph data for user {_userManager.GetUserId(User)}, but user did not exist");
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            // Get the tracks and artists
            VOption<IList<VisifySavedTrack>> stracks = await DatabaseService.GetUsersSavedTracks(user.Id, limit: 10_000);
            if (!stracks.WasSuccess) {
                logger.LogError($"Failed to retreive saved tracks for user {_userManager.GetUserId(User)}", stracks.ErrorMessage);
                return Json("FAILED");
            }

            // create a proper d3 structure
            Dictionary<string, FDGNode> nodes = new Dictionary<string, FDGNode>();
            Dictionary<string, FDGEdge> edges = new Dictionary<string, FDGEdge>();

            foreach (VisifySavedTrack vst in stracks.Value) {
                string tid = $"tid_{vst.VisifyTrack.SpotifyId}";
                string[] idarr = new string[2];
                Stack<string> artistsOnThisTrack = new Stack<string>(vst.VisifyTrack.Artists.Count);
                for (int i = 0; i < vst.VisifyTrack.Artists.Count; i++) {
                    VisifyArtist va = vst.VisifyTrack.Artists[i];
                    if (!nodes.ContainsKey(va.SpotifyId)) {
                        nodes.Add(va.SpotifyId, new FDGNode(va.SpotifyId, 0, va.ArtistName, 1, 1000));
                    }
                    artistsOnThisTrack.Push(va.SpotifyId);
                }

                while(artistsOnThisTrack.Count > 0) {
                    string a = artistsOnThisTrack.Pop();
                    foreach (string othera in artistsOnThisTrack) {
                        idarr[0] = a;
                        idarr[1] = othera;
                        Array.Sort(idarr);
                        string lid0 = String.Join("", idarr);
                        Dictionary<string, string> tn = new Dictionary<string, string>() {
                                {"name", vst.VisifyTrack.TrackName }
                            };
                        if (edges.ContainsKey(lid0)) {
                            edges[lid0].strength += 0.1;
                            edges[lid0].tracks.Add(tn);
                        }
                        else {
                            FDGEdge n = new FDGEdge(othera, a, 0.1);
                            n.tracks.Add(tn);
                            edges.Add(lid0, n);
                        }
                    }
                }
            }

            Dictionary<string, object> keys = new Dictionary<string, object>() {
                {"nodes", nodes.Values },
                {"links", edges.Values }
            };
            return Json(keys);
        }
    }
}

Visify/Views/Graph/ArtistCollabGraph.cshtml
@{
    ViewData["Title"] = "ArtistCollabGraph";
    ViewData["ActivePage"] = ManageNavPagesGraph.ArtistCollabGraph;
    Layout = "~/Views/Graph/_LayoutGraph.cshtml";
}

<div style="background:black; height: 100%; width:100%">
    @*<svg background="red"></svg>
        <div class="menubar">
            <div>
                <button type="button" class="menubutton" onclick="ResetMap()">reset</button>
                <button type="button" class="menubutton" onclick="Recenter()">center</button>
                <button type="button" class="menubutton" onclick="ResetZoom()">reset zoom</button>
            </div>
            <div>
                <label class="menulabel" for="textWhich">Show Labels</label>
                <select id="textWhich" class="menubutton"  onchange="textOnOff()">
                    <option value="0">on</option>
                    <option value="1" selected="selected">off</option>
                    <option value="2">on for highlighted</option>
                    <option value="3">on for non-highlighted</option>
                </select>
            </div>
            <div>
                <label class="menulabel" for="nodesWhich">Show Nodes</label>
                <select id="nodesWhich" class="menubutton" onchange="nodeOnOff()">
                    <option value="0" selected="selected">all nodes</option>
                    <option value="1">only selected nodes</option>
                </select>
            </div>
            <div>
                <button class="menubutton"  onclick="ClearSearchText()">x</button>
                <input class="menubutton"  id="searchText" />
                <button class="menubutton"  onclick="FindNode()">search</button>
            </div>
        </div>*@
    <div class="menubar">
        <div>
            <label for="textWhich">Show Labels</label>
            <select id="textWhich" onchange="textOnOff()">
                <option value="0" selected="selected">on</option>
                <option value="1">on for highlighted</option>
                <option value="2">on for non-highlighted</option>
                <option value="3">off</option>
            </select>
        </div>
        <div>
            <label for="nodesWhich">Show Nodes</label>
            <select id="nodesWhich" onchange="nodeOnOff()">
                <option value="0" selected="selected">all nodes</option>
                <option value="1">only selected nodes</option>
            </select>
        </div>
    </div>
    <div id="graphDiv"></div>
    <div id="tooltip" class="tooltip"></div>
</div>
<script src="~/js/collab_canvas.js">
</script>

Visify/Views/Graph/ArtistSongGroupGraph.cshtml
@{
    ViewData["Title"] = "ArtistSongGroupGraph";
    ViewData["ActivePage"] = ManageNavPagesGraph.ArtistSongGroup;
    Layout = "~/Views/Graph/_LayoutGraph.cshtml";
}

<div style="background:black; height: 100%; width:100%">
    <div class="menubar">
        <div>
            <label for="textWhich">Show Labels</label>
            <select id="textWhich" onchange="textOnOff()">
                <option value="0" selected="selected">on</option>
                <option value="1">on for highlighted</option>
                <option value="2">on for non-highlighted</option>
                <option value="3">off</option>
            </select>
        </div>
        <div>
            <label for="nodesWhich">Show Nodes</label>
            <select id="nodesWhich" onchange="nodeOnOff()">
                <option value="0" selected="selected">all nodes</option>
                <option value="1">only selected nodes</option>
            </select>
        </div>
    </div>
    <div id="graphDiv"></div>
    <div id="tooltip" class="tooltip"></div>
</div>
<script src="~/js/song_canvas.js">
</script>

Visify/Views/Graph/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_LayoutGraph";
}
@{
    ViewData["Title"] = "Ayy";
}

Hello

Visify/Views/Graph/_LayoutGraph.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Visify</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://d3js.org/d3-force.v1.min.js"></script>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <link rel="stylesheet" type="text/css" href="css/vgraph2.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/vgraph.css">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Visify</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="Identity" asp-page="/Account/Manage/Library" title="Manage">Library</a></li>
                    <li><a asp-area="" asp-controller="Graph" asp-action="Index">Graph</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <div class="row vsidebarcontainer">
        <div class="col-md-3 vsidebar">
            <ul class="nav nav-pills nav-stacked">
                <li class="@ManageNavPagesGraph.ArtistCollabGraphNavClass(ViewContext)" style="display: block">
                    <a asp-controller="Graph" asp-action="ArtistCollabGraph">
                        <div class="vbaroption">
                            <img height="64" src="~/images/icon_collab128.png" />
                        </div>
                        <label>Collaboration Graph</label>
                    </a>
                </li>
                <li class="@ManageNavPagesGraph.ArtistSongGroupNavClass(ViewContext)" style="display: block">
                    <a asp-controller="Graph" asp-action="ArtistSongGroupGraph">
                        <div class="vbaroption">
                            <img height="64" src="~/images/icon_group128.png" />
                        </div>
                        <label>Artist Song Graph</label>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col-md-9" style="height: 100%; padding-left:0; padding-right: 0;">
            @RenderBody()
        </div>
    </div>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>